version: "2.1"
services:
  es:
    image: blacktop/elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "apk add curl && curl -f http://localhost:9200"]
      interval: 10s
      timeout: 30s
      retries: 5
      
  redis:
    image: redis
    ports:
      - 6379:6379

  e-search:
    build: .
    ports:
      - 3000:3000
    environment:
      - ELASTIC_NODE=http://es:9200
      - REDIS_URL=redis://redis:6379
      - DROPBOX_TOKEN=<YOUR_TOKEN>
    restart: on-failure
    depends_on:
      redis:
        condition: service_started
      es:
        condition: service_healthy
    links:
      - es
      - redis
